/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AddVideoRequest {
  'title' : string,
  'thumbnail' : [] | [ExternalBlob],
  'collectionId' : [] | [CollectionId],
  'blob' : ExternalBlob,
  'tags' : [] | [Array<string>],
  'description' : string,
  'fileSize' : bigint,
  'filename' : string,
}
export type BatchAction = { 'moveToCollection' : [] | [CollectionId] } |
  { 'delete' : null } |
  { 'addTags' : Array<string> } |
  { 'removeTags' : Array<string> };
export interface BatchVideoActionRequest {
  'action' : BatchAction,
  'videoIds' : Array<VideoId>,
}
export interface Collection {
  'id' : CollectionId,
  'title' : string,
  'owner' : UserId,
  'createdAt' : Timestamp,
}
export type CollectionId = bigint;
export interface CreateShareLinkRequest { 'scope' : ShareScope }
export type DeleteCollectionStrategy = { 'moveToCollection' : CollectionId } |
  { 'deleteVideos' : null } |
  { 'moveToUncategorized' : null };
export type ExternalBlob = Uint8Array;
export interface ShareLink {
  'id' : ShareLinkId,
  'token' : string,
  'owner' : UserId,
  'createdAt' : Timestamp,
  'scope' : ShareScope,
}
export type ShareLinkId = string;
export type ShareScope = { 'tag' : string } |
  { 'collection' : CollectionId } |
  { 'library' : null };
export type SortField = { 'title' : null } |
  { 'fileSize' : null } |
  { 'dateAdded' : null };
export type SortOrder = { 'asc' : null } |
  { 'desc' : null };
export type Timestamp = bigint;
export interface UpdateVideoRequest {
  'id' : VideoId,
  'title' : string,
  'collectionId' : [] | [CollectionId],
  'tags' : [] | [Array<string>],
  'description' : string,
}
export type UserId = Principal;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Video {
  'id' : VideoId,
  'title' : string,
  'thumbnail' : [] | [ExternalBlob],
  'collectionId' : [] | [CollectionId],
  'owner' : UserId,
  'blob' : ExternalBlob,
  'createdAt' : Timestamp,
  'tags' : Array<string>,
  'description' : string,
  'fileSize' : bigint,
  'filename' : string,
}
export interface VideoFilter {
  'sortField' : SortField,
  'dateTo' : [] | [Timestamp],
  'collectionId' : [] | [CollectionId],
  'sortOrder' : SortOrder,
  'tags' : [] | [Array<string>],
  'searchTerm' : [] | [string],
  'dateFrom' : [] | [Timestamp],
}
export type VideoId = bigint;
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addVideo' : ActorMethod<[AddVideoRequest], Video>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'batchVideoAction' : ActorMethod<[BatchVideoActionRequest], bigint>,
  'createCollection' : ActorMethod<[string], Collection>,
  'createShareLink' : ActorMethod<[CreateShareLinkRequest], ShareLink>,
  'deleteCollection' : ActorMethod<
    [CollectionId, DeleteCollectionStrategy],
    boolean
  >,
  'deleteShareLink' : ActorMethod<[ShareLinkId], boolean>,
  'deleteVideo' : ActorMethod<[VideoId], boolean>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getSharedVideos' : ActorMethod<[string], Array<Video>>,
  'getVideo' : ActorMethod<[VideoId], [] | [Video]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listCollections' : ActorMethod<[], Array<Collection>>,
  'listShareLinks' : ActorMethod<[], Array<ShareLink>>,
  'listVideos' : ActorMethod<[VideoFilter], Array<Video>>,
  'moveVideo' : ActorMethod<[VideoId, [] | [CollectionId]], boolean>,
  'renameCollection' : ActorMethod<[CollectionId, string], boolean>,
  'updateVideo' : ActorMethod<[UpdateVideoRequest], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];