/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const CollectionId = IDL.Nat;
export const AddVideoRequest = IDL.Record({
  'title' : IDL.Text,
  'thumbnail' : IDL.Opt(ExternalBlob),
  'collectionId' : IDL.Opt(CollectionId),
  'blob' : ExternalBlob,
  'tags' : IDL.Opt(IDL.Vec(IDL.Text)),
  'description' : IDL.Text,
  'fileSize' : IDL.Nat,
  'filename' : IDL.Text,
});
export const VideoId = IDL.Nat;
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const Video = IDL.Record({
  'id' : VideoId,
  'title' : IDL.Text,
  'thumbnail' : IDL.Opt(ExternalBlob),
  'collectionId' : IDL.Opt(CollectionId),
  'owner' : UserId,
  'blob' : ExternalBlob,
  'createdAt' : Timestamp,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'fileSize' : IDL.Nat,
  'filename' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BatchAction = IDL.Variant({
  'moveToCollection' : IDL.Opt(CollectionId),
  'delete' : IDL.Null,
  'addTags' : IDL.Vec(IDL.Text),
  'removeTags' : IDL.Vec(IDL.Text),
});
export const BatchVideoActionRequest = IDL.Record({
  'action' : BatchAction,
  'videoIds' : IDL.Vec(VideoId),
});
export const Collection = IDL.Record({
  'id' : CollectionId,
  'title' : IDL.Text,
  'owner' : UserId,
  'createdAt' : Timestamp,
});
export const ShareScope = IDL.Variant({
  'tag' : IDL.Text,
  'collection' : CollectionId,
  'library' : IDL.Null,
});
export const CreateShareLinkRequest = IDL.Record({ 'scope' : ShareScope });
export const ShareLinkId = IDL.Text;
export const ShareLink = IDL.Record({
  'id' : ShareLinkId,
  'token' : IDL.Text,
  'owner' : UserId,
  'createdAt' : Timestamp,
  'scope' : ShareScope,
});
export const DeleteCollectionStrategy = IDL.Variant({
  'moveToCollection' : CollectionId,
  'deleteVideos' : IDL.Null,
  'moveToUncategorized' : IDL.Null,
});
export const SortField = IDL.Variant({
  'title' : IDL.Null,
  'fileSize' : IDL.Null,
  'dateAdded' : IDL.Null,
});
export const SortOrder = IDL.Variant({ 'asc' : IDL.Null, 'desc' : IDL.Null });
export const VideoFilter = IDL.Record({
  'sortField' : SortField,
  'dateTo' : IDL.Opt(Timestamp),
  'collectionId' : IDL.Opt(CollectionId),
  'sortOrder' : SortOrder,
  'tags' : IDL.Opt(IDL.Vec(IDL.Text)),
  'searchTerm' : IDL.Opt(IDL.Text),
  'dateFrom' : IDL.Opt(Timestamp),
});
export const UpdateVideoRequest = IDL.Record({
  'id' : VideoId,
  'title' : IDL.Text,
  'collectionId' : IDL.Opt(CollectionId),
  'tags' : IDL.Opt(IDL.Vec(IDL.Text)),
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addVideo' : IDL.Func([AddVideoRequest], [Video], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'batchVideoAction' : IDL.Func([BatchVideoActionRequest], [IDL.Nat], []),
  'createCollection' : IDL.Func([IDL.Text], [Collection], []),
  'createShareLink' : IDL.Func([CreateShareLinkRequest], [ShareLink], []),
  'deleteCollection' : IDL.Func(
      [CollectionId, DeleteCollectionStrategy],
      [IDL.Bool],
      [],
    ),
  'deleteShareLink' : IDL.Func([ShareLinkId], [IDL.Bool], []),
  'deleteVideo' : IDL.Func([VideoId], [IDL.Bool], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getSharedVideos' : IDL.Func([IDL.Text], [IDL.Vec(Video)], ['query']),
  'getVideo' : IDL.Func([VideoId], [IDL.Opt(Video)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listCollections' : IDL.Func([], [IDL.Vec(Collection)], ['query']),
  'listShareLinks' : IDL.Func([], [IDL.Vec(ShareLink)], ['query']),
  'listVideos' : IDL.Func([VideoFilter], [IDL.Vec(Video)], ['query']),
  'moveVideo' : IDL.Func([VideoId, IDL.Opt(CollectionId)], [IDL.Bool], []),
  'renameCollection' : IDL.Func([CollectionId, IDL.Text], [IDL.Bool], []),
  'updateVideo' : IDL.Func([UpdateVideoRequest], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const CollectionId = IDL.Nat;
  const AddVideoRequest = IDL.Record({
    'title' : IDL.Text,
    'thumbnail' : IDL.Opt(ExternalBlob),
    'collectionId' : IDL.Opt(CollectionId),
    'blob' : ExternalBlob,
    'tags' : IDL.Opt(IDL.Vec(IDL.Text)),
    'description' : IDL.Text,
    'fileSize' : IDL.Nat,
    'filename' : IDL.Text,
  });
  const VideoId = IDL.Nat;
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const Video = IDL.Record({
    'id' : VideoId,
    'title' : IDL.Text,
    'thumbnail' : IDL.Opt(ExternalBlob),
    'collectionId' : IDL.Opt(CollectionId),
    'owner' : UserId,
    'blob' : ExternalBlob,
    'createdAt' : Timestamp,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'fileSize' : IDL.Nat,
    'filename' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BatchAction = IDL.Variant({
    'moveToCollection' : IDL.Opt(CollectionId),
    'delete' : IDL.Null,
    'addTags' : IDL.Vec(IDL.Text),
    'removeTags' : IDL.Vec(IDL.Text),
  });
  const BatchVideoActionRequest = IDL.Record({
    'action' : BatchAction,
    'videoIds' : IDL.Vec(VideoId),
  });
  const Collection = IDL.Record({
    'id' : CollectionId,
    'title' : IDL.Text,
    'owner' : UserId,
    'createdAt' : Timestamp,
  });
  const ShareScope = IDL.Variant({
    'tag' : IDL.Text,
    'collection' : CollectionId,
    'library' : IDL.Null,
  });
  const CreateShareLinkRequest = IDL.Record({ 'scope' : ShareScope });
  const ShareLinkId = IDL.Text;
  const ShareLink = IDL.Record({
    'id' : ShareLinkId,
    'token' : IDL.Text,
    'owner' : UserId,
    'createdAt' : Timestamp,
    'scope' : ShareScope,
  });
  const DeleteCollectionStrategy = IDL.Variant({
    'moveToCollection' : CollectionId,
    'deleteVideos' : IDL.Null,
    'moveToUncategorized' : IDL.Null,
  });
  const SortField = IDL.Variant({
    'title' : IDL.Null,
    'fileSize' : IDL.Null,
    'dateAdded' : IDL.Null,
  });
  const SortOrder = IDL.Variant({ 'asc' : IDL.Null, 'desc' : IDL.Null });
  const VideoFilter = IDL.Record({
    'sortField' : SortField,
    'dateTo' : IDL.Opt(Timestamp),
    'collectionId' : IDL.Opt(CollectionId),
    'sortOrder' : SortOrder,
    'tags' : IDL.Opt(IDL.Vec(IDL.Text)),
    'searchTerm' : IDL.Opt(IDL.Text),
    'dateFrom' : IDL.Opt(Timestamp),
  });
  const UpdateVideoRequest = IDL.Record({
    'id' : VideoId,
    'title' : IDL.Text,
    'collectionId' : IDL.Opt(CollectionId),
    'tags' : IDL.Opt(IDL.Vec(IDL.Text)),
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addVideo' : IDL.Func([AddVideoRequest], [Video], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'batchVideoAction' : IDL.Func([BatchVideoActionRequest], [IDL.Nat], []),
    'createCollection' : IDL.Func([IDL.Text], [Collection], []),
    'createShareLink' : IDL.Func([CreateShareLinkRequest], [ShareLink], []),
    'deleteCollection' : IDL.Func(
        [CollectionId, DeleteCollectionStrategy],
        [IDL.Bool],
        [],
      ),
    'deleteShareLink' : IDL.Func([ShareLinkId], [IDL.Bool], []),
    'deleteVideo' : IDL.Func([VideoId], [IDL.Bool], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getSharedVideos' : IDL.Func([IDL.Text], [IDL.Vec(Video)], ['query']),
    'getVideo' : IDL.Func([VideoId], [IDL.Opt(Video)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listCollections' : IDL.Func([], [IDL.Vec(Collection)], ['query']),
    'listShareLinks' : IDL.Func([], [IDL.Vec(ShareLink)], ['query']),
    'listVideos' : IDL.Func([VideoFilter], [IDL.Vec(Video)], ['query']),
    'moveVideo' : IDL.Func([VideoId, IDL.Opt(CollectionId)], [IDL.Bool], []),
    'renameCollection' : IDL.Func([CollectionId, IDL.Text], [IDL.Bool], []),
    'updateVideo' : IDL.Func([UpdateVideoRequest], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };