/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Video {
    id: VideoId;
    title: string;
    thumbnail?: ExternalBlob;
    collectionId?: CollectionId;
    owner: UserId;
    blob: ExternalBlob;
    createdAt: Timestamp;
    tags: Array<string>;
    description: string;
    fileSize: bigint;
    filename: string;
}
export type ShareScope = {
    __kind__: "tag";
    tag: string;
} | {
    __kind__: "collection";
    collection: CollectionId;
} | {
    __kind__: "library";
    library: null;
};
export type Timestamp = bigint;
export interface VideoFilter {
    sortField: SortField;
    dateTo?: Timestamp;
    collectionId?: CollectionId;
    sortOrder: SortOrder;
    tags?: Array<string>;
    searchTerm?: string;
    dateFrom?: Timestamp;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface UpdateVideoRequest {
    id: VideoId;
    title: string;
    collectionId?: CollectionId;
    tags?: Array<string>;
    description: string;
}
export type DeleteCollectionStrategy = {
    __kind__: "moveToCollection";
    moveToCollection: CollectionId;
} | {
    __kind__: "deleteVideos";
    deleteVideos: null;
} | {
    __kind__: "moveToUncategorized";
    moveToUncategorized: null;
};
export interface BatchVideoActionRequest {
    action: BatchAction;
    videoIds: Array<VideoId>;
}
export type BatchAction = {
    __kind__: "moveToCollection";
    moveToCollection: CollectionId | null;
} | {
    __kind__: "delete";
    delete: null;
} | {
    __kind__: "addTags";
    addTags: Array<string>;
} | {
    __kind__: "removeTags";
    removeTags: Array<string>;
};
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface AddVideoRequest {
    title: string;
    thumbnail?: ExternalBlob;
    collectionId?: CollectionId;
    blob: ExternalBlob;
    tags?: Array<string>;
    description: string;
    fileSize: bigint;
    filename: string;
}
export type UserId = Principal;
export type ShareLinkId = string;
export interface Collection {
    id: CollectionId;
    title: string;
    owner: UserId;
    createdAt: Timestamp;
}
export interface ShareLink {
    id: ShareLinkId;
    token: string;
    owner: UserId;
    createdAt: Timestamp;
    scope: ShareScope;
}
export type VideoId = bigint;
export type CollectionId = bigint;
export interface CreateShareLinkRequest {
    scope: ShareScope;
}
export enum SortField {
    title = "title",
    fileSize = "fileSize",
    dateAdded = "dateAdded"
}
export enum SortOrder {
    asc = "asc",
    desc = "desc"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    addVideo(req: AddVideoRequest): Promise<Video>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    batchVideoAction(req: BatchVideoActionRequest): Promise<bigint>;
    createCollection(title: string): Promise<Collection>;
    createShareLink(req: CreateShareLinkRequest): Promise<ShareLink>;
    deleteCollection(id: CollectionId, strategy: DeleteCollectionStrategy): Promise<boolean>;
    deleteShareLink(id: ShareLinkId): Promise<boolean>;
    deleteVideo(id: VideoId): Promise<boolean>;
    getCallerUserRole(): Promise<UserRole>;
    getSharedVideos(token: string): Promise<Array<Video>>;
    getVideo(id: VideoId): Promise<Video | null>;
    isCallerAdmin(): Promise<boolean>;
    listCollections(): Promise<Array<Collection>>;
    listShareLinks(): Promise<Array<ShareLink>>;
    listVideos(filter: VideoFilter): Promise<Array<Video>>;
    moveVideo(videoId: VideoId, collectionId: CollectionId | null): Promise<boolean>;
    renameCollection(id: CollectionId, newTitle: string): Promise<boolean>;
    updateVideo(req: UpdateVideoRequest): Promise<boolean>;
}
import type { AddVideoRequest as _AddVideoRequest, BatchAction as _BatchAction, BatchVideoActionRequest as _BatchVideoActionRequest, CollectionId as _CollectionId, CreateShareLinkRequest as _CreateShareLinkRequest, DeleteCollectionStrategy as _DeleteCollectionStrategy, ExternalBlob as _ExternalBlob, ShareLink as _ShareLink, ShareLinkId as _ShareLinkId, ShareScope as _ShareScope, SortField as _SortField, SortOrder as _SortOrder, Timestamp as _Timestamp, UpdateVideoRequest as _UpdateVideoRequest, UserId as _UserId, UserRole as _UserRole, Video as _Video, VideoFilter as _VideoFilter, VideoId as _VideoId, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addVideo(arg0: AddVideoRequest): Promise<Video> {
        if (this.processError) {
            try {
                const result = await this.actor.addVideo(await to_candid_AddVideoRequest_n8(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Video_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addVideo(await to_candid_AddVideoRequest_n8(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Video_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n16(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n16(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async batchVideoAction(arg0: BatchVideoActionRequest): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.batchVideoAction(to_candid_BatchVideoActionRequest_n18(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.batchVideoAction(to_candid_BatchVideoActionRequest_n18(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createCollection(arg0: string): Promise<Collection> {
        if (this.processError) {
            try {
                const result = await this.actor.createCollection(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCollection(arg0);
            return result;
        }
    }
    async createShareLink(arg0: CreateShareLinkRequest): Promise<ShareLink> {
        if (this.processError) {
            try {
                const result = await this.actor.createShareLink(to_candid_CreateShareLinkRequest_n22(this._uploadFile, this._downloadFile, arg0));
                return from_candid_ShareLink_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createShareLink(to_candid_CreateShareLinkRequest_n22(this._uploadFile, this._downloadFile, arg0));
            return from_candid_ShareLink_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteCollection(arg0: CollectionId, arg1: DeleteCollectionStrategy): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCollection(arg0, to_candid_DeleteCollectionStrategy_n30(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCollection(arg0, to_candid_DeleteCollectionStrategy_n30(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteShareLink(arg0: ShareLinkId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteShareLink(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteShareLink(arg0);
            return result;
        }
    }
    async deleteVideo(arg0: VideoId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVideo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVideo(arg0);
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSharedVideos(arg0: string): Promise<Array<Video>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSharedVideos(arg0);
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSharedVideos(arg0);
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVideo(arg0: VideoId): Promise<Video | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVideo(arg0);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVideo(arg0);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listCollections(): Promise<Array<Collection>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCollections();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCollections();
            return result;
        }
    }
    async listShareLinks(): Promise<Array<ShareLink>> {
        if (this.processError) {
            try {
                const result = await this.actor.listShareLinks();
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listShareLinks();
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async listVideos(arg0: VideoFilter): Promise<Array<Video>> {
        if (this.processError) {
            try {
                const result = await this.actor.listVideos(to_candid_VideoFilter_n37(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listVideos(to_candid_VideoFilter_n37(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async moveVideo(arg0: VideoId, arg1: CollectionId | null): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.moveVideo(arg0, to_candid_opt_n43(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.moveVideo(arg0, to_candid_opt_n43(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async renameCollection(arg0: CollectionId, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.renameCollection(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.renameCollection(arg0, arg1);
            return result;
        }
    }
    async updateVideo(arg0: UpdateVideoRequest): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVideo(to_candid_UpdateVideoRequest_n44(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVideo(to_candid_UpdateVideoRequest_n44(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
async function from_candid_ExternalBlob_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_ShareLink_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ShareLink): ShareLink {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_ShareScope_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ShareScope): ShareScope {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
async function from_candid_Video_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Video): Promise<Video> {
    return await from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CollectionId]): CollectionId | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Video]): Promise<Video | null> {
    return value.length === 0 ? null : await from_candid_Video_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _VideoId;
    title: string;
    thumbnail: [] | [_ExternalBlob];
    collectionId: [] | [_CollectionId];
    owner: _UserId;
    blob: _ExternalBlob;
    createdAt: _Timestamp;
    tags: Array<string>;
    description: string;
    fileSize: bigint;
    filename: string;
}): Promise<{
    id: VideoId;
    title: string;
    thumbnail?: ExternalBlob;
    collectionId?: CollectionId;
    owner: UserId;
    blob: ExternalBlob;
    createdAt: Timestamp;
    tags: Array<string>;
    description: string;
    fileSize: bigint;
    filename: string;
}> {
    return {
        id: value.id,
        title: value.title,
        thumbnail: record_opt_to_undefined(await from_candid_opt_n13(_uploadFile, _downloadFile, value.thumbnail)),
        collectionId: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.collectionId)),
        owner: value.owner,
        blob: await from_candid_ExternalBlob_n14(_uploadFile, _downloadFile, value.blob),
        createdAt: value.createdAt,
        tags: value.tags,
        description: value.description,
        fileSize: value.fileSize,
        filename: value.filename
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ShareLinkId;
    token: string;
    owner: _UserId;
    createdAt: _Timestamp;
    scope: _ShareScope;
}): {
    id: ShareLinkId;
    token: string;
    owner: UserId;
    createdAt: Timestamp;
    scope: ShareScope;
} {
    return {
        id: value.id,
        token: value.token,
        owner: value.owner,
        createdAt: value.createdAt,
        scope: from_candid_ShareScope_n28(_uploadFile, _downloadFile, value.scope)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tag: string;
} | {
    collection: _CollectionId;
} | {
    library: null;
}): {
    __kind__: "tag";
    tag: string;
} | {
    __kind__: "collection";
    collection: CollectionId;
} | {
    __kind__: "library";
    library: null;
} {
    return "tag" in value ? {
        __kind__: "tag",
        tag: value.tag
    } : "collection" in value ? {
        __kind__: "collection",
        collection: value.collection
    } : "library" in value ? {
        __kind__: "library",
        library: value.library
    } : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Video>): Promise<Array<Video>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Video_n11(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ShareLink>): Array<ShareLink> {
    return value.map((x)=>from_candid_ShareLink_n26(_uploadFile, _downloadFile, x));
}
async function to_candid_AddVideoRequest_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AddVideoRequest): Promise<_AddVideoRequest> {
    return await to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_BatchAction_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BatchAction): _BatchAction {
    return to_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function to_candid_BatchVideoActionRequest_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BatchVideoActionRequest): _BatchVideoActionRequest {
    return to_candid_record_n19(_uploadFile, _downloadFile, value);
}
function to_candid_CreateShareLinkRequest_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateShareLinkRequest): _CreateShareLinkRequest {
    return to_candid_record_n23(_uploadFile, _downloadFile, value);
}
function to_candid_DeleteCollectionStrategy_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DeleteCollectionStrategy): _DeleteCollectionStrategy {
    return to_candid_variant_n31(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_ShareScope_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ShareScope): _ShareScope {
    return to_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function to_candid_SortField_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SortField): _SortField {
    return to_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function to_candid_SortOrder_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SortOrder): _SortOrder {
    return to_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateVideoRequest_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateVideoRequest): _UpdateVideoRequest {
    return to_candid_record_n45(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_VideoFilter_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VideoFilter): _VideoFilter {
    return to_candid_record_n38(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CollectionId | null): [] | [_CollectionId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    action: BatchAction;
    videoIds: Array<VideoId>;
}): {
    action: _BatchAction;
    videoIds: Array<_VideoId>;
} {
    return {
        action: to_candid_BatchAction_n20(_uploadFile, _downloadFile, value.action),
        videoIds: value.videoIds
    };
}
function to_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    scope: ShareScope;
}): {
    scope: _ShareScope;
} {
    return {
        scope: to_candid_ShareScope_n24(_uploadFile, _downloadFile, value.scope)
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sortField: SortField;
    dateTo?: Timestamp;
    collectionId?: CollectionId;
    sortOrder: SortOrder;
    tags?: Array<string>;
    searchTerm?: string;
    dateFrom?: Timestamp;
}): {
    sortField: _SortField;
    dateTo: [] | [_Timestamp];
    collectionId: [] | [_CollectionId];
    sortOrder: _SortOrder;
    tags: [] | [Array<string>];
    searchTerm: [] | [string];
    dateFrom: [] | [_Timestamp];
} {
    return {
        sortField: to_candid_SortField_n39(_uploadFile, _downloadFile, value.sortField),
        dateTo: value.dateTo ? candid_some(value.dateTo) : candid_none(),
        collectionId: value.collectionId ? candid_some(value.collectionId) : candid_none(),
        sortOrder: to_candid_SortOrder_n41(_uploadFile, _downloadFile, value.sortOrder),
        tags: value.tags ? candid_some(value.tags) : candid_none(),
        searchTerm: value.searchTerm ? candid_some(value.searchTerm) : candid_none(),
        dateFrom: value.dateFrom ? candid_some(value.dateFrom) : candid_none()
    };
}
function to_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: VideoId;
    title: string;
    collectionId?: CollectionId;
    tags?: Array<string>;
    description: string;
}): {
    id: _VideoId;
    title: string;
    collectionId: [] | [_CollectionId];
    tags: [] | [Array<string>];
    description: string;
} {
    return {
        id: value.id,
        title: value.title,
        collectionId: value.collectionId ? candid_some(value.collectionId) : candid_none(),
        tags: value.tags ? candid_some(value.tags) : candid_none(),
        description: value.description
    };
}
async function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    thumbnail?: ExternalBlob;
    collectionId?: CollectionId;
    blob: ExternalBlob;
    tags?: Array<string>;
    description: string;
    fileSize: bigint;
    filename: string;
}): Promise<{
    title: string;
    thumbnail: [] | [_ExternalBlob];
    collectionId: [] | [_CollectionId];
    blob: _ExternalBlob;
    tags: [] | [Array<string>];
    description: string;
    fileSize: bigint;
    filename: string;
}> {
    return {
        title: value.title,
        thumbnail: value.thumbnail ? candid_some(await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.thumbnail)) : candid_none(),
        collectionId: value.collectionId ? candid_some(value.collectionId) : candid_none(),
        blob: await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.blob),
        tags: value.tags ? candid_some(value.tags) : candid_none(),
        description: value.description,
        fileSize: value.fileSize,
        filename: value.filename
    };
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "moveToCollection";
    moveToCollection: CollectionId | null;
} | {
    __kind__: "delete";
    delete: null;
} | {
    __kind__: "addTags";
    addTags: Array<string>;
} | {
    __kind__: "removeTags";
    removeTags: Array<string>;
}): {
    moveToCollection: [] | [_CollectionId];
} | {
    delete: null;
} | {
    addTags: Array<string>;
} | {
    removeTags: Array<string>;
} {
    return value.__kind__ === "moveToCollection" ? {
        moveToCollection: value.moveToCollection ? candid_some(value.moveToCollection) : candid_none()
    } : value.__kind__ === "delete" ? {
        delete: value.delete
    } : value.__kind__ === "addTags" ? {
        addTags: value.addTags
    } : value.__kind__ === "removeTags" ? {
        removeTags: value.removeTags
    } : value;
}
function to_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "tag";
    tag: string;
} | {
    __kind__: "collection";
    collection: CollectionId;
} | {
    __kind__: "library";
    library: null;
}): {
    tag: string;
} | {
    collection: _CollectionId;
} | {
    library: null;
} {
    return value.__kind__ === "tag" ? {
        tag: value.tag
    } : value.__kind__ === "collection" ? {
        collection: value.collection
    } : value.__kind__ === "library" ? {
        library: value.library
    } : value;
}
function to_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "moveToCollection";
    moveToCollection: CollectionId;
} | {
    __kind__: "deleteVideos";
    deleteVideos: null;
} | {
    __kind__: "moveToUncategorized";
    moveToUncategorized: null;
}): {
    moveToCollection: _CollectionId;
} | {
    deleteVideos: null;
} | {
    moveToUncategorized: null;
} {
    return value.__kind__ === "moveToCollection" ? {
        moveToCollection: value.moveToCollection
    } : value.__kind__ === "deleteVideos" ? {
        deleteVideos: value.deleteVideos
    } : value.__kind__ === "moveToUncategorized" ? {
        moveToUncategorized: value.moveToUncategorized
    } : value;
}
function to_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SortField): {
    title: null;
} | {
    fileSize: null;
} | {
    dateAdded: null;
} {
    return value == SortField.title ? {
        title: null
    } : value == SortField.fileSize ? {
        fileSize: null
    } : value == SortField.dateAdded ? {
        dateAdded: null
    } : value;
}
function to_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SortOrder): {
    asc: null;
} | {
    desc: null;
} {
    return value == SortOrder.asc ? {
        asc: null
    } : value == SortOrder.desc ? {
        desc: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
