/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by TanStack Router.
// It should not be edited manually.

// Import the root route
import { Route as rootRoute } from "./routes/__root";

import { Route as CollectionsImport } from "./routes/collections";
// Import each route
import { Route as IndexImport } from "./routes/index";
import { Route as SharedTokenImport } from "./routes/shared.$token";
import { Route as UploadImport } from "./routes/upload";
import { Route as VideoIdImport } from "./routes/video.$id";

// Construct the route tree
const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

const UploadRoute = UploadImport.update({
  id: "/upload",
  path: "/upload",
  getParentRoute: () => rootRoute,
} as any);

const CollectionsRoute = CollectionsImport.update({
  id: "/collections",
  path: "/collections",
  getParentRoute: () => rootRoute,
} as any);

const VideoIdRoute = VideoIdImport.update({
  id: "/video/$id",
  path: "/video/$id",
  getParentRoute: () => rootRoute,
} as any);

const SharedTokenRoute = SharedTokenImport.update({
  id: "/shared/$token",
  path: "/shared/$token",
  getParentRoute: () => rootRoute,
} as any);

// Augment the module for type-safe routing
declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/upload": {
      id: "/upload";
      path: "/upload";
      fullPath: "/upload";
      preLoaderRoute: typeof UploadImport;
      parentRoute: typeof rootRoute;
    };
    "/collections": {
      id: "/collections";
      path: "/collections";
      fullPath: "/collections";
      preLoaderRoute: typeof CollectionsImport;
      parentRoute: typeof rootRoute;
    };
    "/video/$id": {
      id: "/video/$id";
      path: "/video/$id";
      fullPath: "/video/$id";
      preLoaderRoute: typeof VideoIdImport;
      parentRoute: typeof rootRoute;
    };
    "/shared/$token": {
      id: "/shared/$token";
      path: "/shared/$token";
      fullPath: "/shared/$token";
      preLoaderRoute: typeof SharedTokenImport;
      parentRoute: typeof rootRoute;
    };
  }
}

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  UploadRoute,
  CollectionsRoute,
  VideoIdRoute,
  SharedTokenRoute,
});
